import Mathlib.AlgebraicTopology.SimplexCategory.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.UnitaryGroup


/-!
# The double covering `SU(2) → SO(3)`
This file formalizes Definition 14 and Theorem 15 from the supplied notes.  We use
Mathlib's matrix definitions of the special unitary and special orthogonal groups.
The notes construct the covering map by identifying `SU(2)` with the unit
quaternions and sending `q` to the rotation `x ↦ qxq⁻¹`.  Definition 14 packages
exactly the two properties of that construction used in Theorem 15: surjectivity
and kernel `{±I₂}`.
-/

open Matrix

namespace Def14ToTheorem15

/-- The matrix group `SU(2)`. -/
abbrev SU2 := specialUnitaryGroup (Fin 2) ℂ

/-- The matrix group `SO(3)`. -/
abbrev SO3 := specialOrthogonalGroup (Fin 3) ℝ

/-- The scalar matrix `-I₂`, regarded as an element of `SU(2)`. -/
def minusI : SU2 := ⟨-1, by
  rw [Matrix.mem_specialUnitaryGroup_iff, Matrix.mem_unitaryGroup_iff]
  constructor
  · ext i j
    fin_cases i <;> fin_cases j <;> simp
  · simp [Matrix.det_fin_two]⟩

/-- The central normal subgroup `{I₂, -I₂}` of `SU(2)`, written intrinsically as
the normal subgroup generated by `-I₂`. -/
def plusMinusI : Subgroup SU2 :=
  Subgroup.normalClosure ({minusI} : Set SU2)

instance plusMinusI_normal : plusMinusI.Normal := by
  unfold plusMinusI
  infer_instance

/-- Membership in `plusMinusI` has the expected concrete description. -/
theorem mem_plusMinusI_iff (U : SU2) :
    U ∈ plusMinusI ↔ U = 1 ∨ U = minusI := by
  refine' ⟨fun hU => _, _⟩
  · refine' Subgroup.closure_induction ( fun x hx => _ ) _ _ _ hU;
    · simp_all +decide [ Group.conjugatesOfSet ];
      obtain ⟨ g, hg ⟩ := hx;
      have h_central : ∀ g : SU2, g * minusI = minusI * g := by
        simp +decide [ minusI ];
      simp_all +decide [ SemiconjBy ];
    · exact Or.inl rfl;
    · rintro x y hx hy ( rfl | rfl ) ( rfl | rfl ) <;> simp +decide;
      exact Or.inl (Subtype.ext <| by
        ext i j
        fin_cases i <;> fin_cases j <;> norm_num [minusI])
    · rintro x hx ( rfl | rfl ) <;> norm_num [ minusI ];
      erw [Subtype.mk_eq_mk]
      norm_num [Matrix.inv_def]
  · rintro (rfl | rfl)
    · exact Subgroup.one_mem _
    · exact Subgroup.subset_normalClosure (Set.mem_singleton _)

/-- **Definition 14.** A realization of the standard double covering
`SU(2) → SO(3)`: a surjective homomorphism whose kernel is exactly `{±I₂}`.
The quaternionic construction in the notes supplies such a realization by
`q ↦ (x ↦ q * x * q⁻¹)` on the pure imaginary quaternions. -/
structure SU2SO3DoubleCover where
  /-- The covering homomorphism. -/
  toMonoidHom : SU2 →* SO3
  /-- Every rotation is induced by a unit quaternion. -/
  surjective : Function.Surjective toMonoidHom
  /-- The only unit quaternions inducing the identity rotation are `±1`. -/
  ker_eq_plusMinusI : toMonoidHom.ker = plusMinusI

namespace SU2SO3DoubleCover

variable (π : SU2SO3DoubleCover)

/-- The fiber over the identity is `{±I₂}`. -/
theorem kernel_eq : π.toMonoidHom.ker = plusMinusI :=
  π.ker_eq_plusMinusI

/-- The image of the double covering is all of `SO(3)`. -/
theorem range_eq_top : π.toMonoidHom.range = ⊤ := by
  ext R
  simp only [Subgroup.mem_top, iff_true]
  exact π.surjective R

/-- The first-isomorphism-theorem form appearing immediately before Theorem 15
in the notes: `SU(2) / ker(π) ≃ SO(3)`. -/
noncomputable def quotientKernelEquivSO3 :
    SU2 ⧸ π.toMonoidHom.ker ≃* SO3 :=
  QuotientGroup.quotientKerEquivOfSurjective π.toMonoidHom π.surjective

/-- **Theorem 15.** The quotient of `SU(2)` by its central subgroup
`{±I₂}` is isomorphic to `SO(3)`. -/
noncomputable def quotientPlusMinusIEquivSO3 :
    SU2 ⧸ plusMinusI ≃* SO3 :=
  (QuotientGroup.quotientMulEquivOfEq π.ker_eq_plusMinusI.symm).trans
    (quotientKernelEquivSO3 π)

/-- A proposition-valued version of Theorem 15, convenient when only existence
of the isomorphism is needed. -/
theorem theorem15 (π : SU2SO3DoubleCover) :
    Nonempty (SU2 ⧸ plusMinusI ≃* SO3) :=
  ⟨quotientPlusMinusIEquivSO3 π⟩

end SU2SO3DoubleCover

end Def14ToTheorem15

#min_imports
